In [154]:
from json_parser import JsonParser
parser = JsonParser()
# parsedFile = parser.files[0]
# print("--- Fichier analys√© : " + parsedFile)
print("--- Fichiers analys√©s : \n" + '\n'.join(parser.files))
parser.extract_from_json()

--- Fichiers analys√©s :
/Users/billy/Documents/workspace/FIL/A3/Openstack-SQL/OpenstackSQLAnalyzer/src/../files/trace-create-and-delete-image.yaml.json
Total joins : 81
Total transactions : 0
---------------------------
trace-create-and-delete-image.yaml.json
---------------------------
Name : wsgi
Count : 10
Duration : 294101

Name : db
Count : 127
Duration : 354

---------------------------
HTTP_COMPONENT
Name : wsgi
Project : keystone
Duration : 0:00:00.005443
Trace id : e1ab54d3-04f5-4c55-aa12-b1007d821680
Parent id : 82fb63df-3ba0-4c53-b6fb-3b0f13f944c1
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Path : /v3
Scheme : http
Method : GET
Query :

HTTP_COMPONENT
Name : wsgi
Project : keystone
Duration : 0:00:00.005318
Trace id : 15ee3859-0bfd-4322-add0-eea252b3625b
Parent id : 82fb63df-3ba0-4c53-b6fb-3b0f13f944c1
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Path : /v3
Scheme : http
Method : GET
Query :

HTTP_COMPONENT
Name : wsgi
Project : keystone
Duration : 0:00:00.428750
Trace id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Parent id : 82fb63df-3ba0-4c53-b6fb-3b0f13f944c1
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Path : /v3/auth/tokens
Scheme : http
Method : POST
Query :
DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001762
Trace id : 78acbf41-ed63-4677-b9ca-520884fe2908
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT name FROM (SELECT name FROM agentinformation)
DB_Stats
Nb join : 0
Nb transactions : 0
{}

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002385
Trace id : 0dda7353-277f-4fde-a1d7-a4f89326258e
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT user.enabled AS user_enabled, user.id AS user_id, user.domain_id AS user_domain_id, user.extra AS user_extra, user.default_project_id AS user_default_project_id, user.created_at AS user_created_at, user.last_active_at AS user_last_active_at
FROM user INNER JOIN local_user ON user.id = local_user.user_id AND user.domain_id = local_user.domain_id
WHERE local_user.name = %(name_1)s AND local_user.domain_id = %(domain_id_1)s
DB_Stats
Nb join : 1
Nb transactions : 0
{domain_id_1, name_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002356
Trace id : 3a9b8239-0dd0-450c-9004-99359c1c0489
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT federated_user.id AS federated_user_id, federated_user.user_id AS federated_user_user_id, federated_user.idp_id AS federated_user_idp_id, federated_user.protocol_id AS federated_user_protocol_id, federated_user.unique_id AS federated_user_unique_id, federated_user.display_name AS federated_user_display_name, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.id AS user_id
FROM user INNER JOIN local_user ON user.id = local_user.user_id AND user.domain_id = local_user.domain_id
WHERE local_user.name = %(name_1)s AND local_user.domain_id = %(domain_id_1)s) AS anon_1 INNER JOIN federated_user ON anon_1.user_id = federated_user.user_id ORDER BY anon_1.user_id
DB_Stats
Nb join : 2
Nb transactions : 0
{domain_id_1, name_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002018
Trace id : d438f7f6-1fe1-4788-9ba0-968fbc67525b
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT user_option.user_id AS user_option_user_id, user_option.option_id AS user_option_option_id, user_option.option_value AS user_option_option_value, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.id AS user_id
FROM user INNER JOIN local_user ON user.id = local_user.user_id AND user.domain_id = local_user.domain_id
WHERE local_user.name = %(name_1)s AND local_user.domain_id = %(domain_id_1)s) AS anon_1 INNER JOIN user_option ON anon_1.user_id = user_option.user_id ORDER BY anon_1.user_id
DB_Stats
Nb join : 2
Nb transactions : 0
{domain_id_1, name_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002049
Trace id : 6c535f4a-b63f-4c60-9d03-5f448e70f33b
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT nonlocal_user.domain_id AS nonlocal_user_domain_id, nonlocal_user.name AS nonlocal_user_name, nonlocal_user.user_id AS nonlocal_user_user_id, anon_1.user_domain_id AS anon_1_user_domain_id, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.domain_id AS user_domain_id, user.id AS user_id
FROM user INNER JOIN local_user ON user.id = local_user.user_id AND user.domain_id = local_user.domain_id
WHERE local_user.name = %(name_1)s AND local_user.domain_id = %(domain_id_1)s) AS anon_1 INNER JOIN nonlocal_user ON anon_1.user_domain_id = nonlocal_user.domain_id AND anon_1.user_id = nonlocal_user.user_id ORDER BY anon_1.user_domain_id, anon_1.user_id
DB_Stats
Nb join : 2
Nb transactions : 0
{domain_id_1, name_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002315
Trace id : 3806c1f7-8752-49f9-8602-4f2380fc0c4e
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT local_user.id AS local_user_id, local_user.user_id AS local_user_user_id, local_user.domain_id AS local_user_domain_id, local_user.name AS local_user_name, local_user.failed_auth_count AS local_user_failed_auth_count, local_user.failed_auth_at AS local_user_failed_auth_at, anon_1.user_id AS anon_1_user_id, anon_1.user_domain_id AS anon_1_user_domain_id
FROM (SELECT user.id AS user_id, user.domain_id AS user_domain_id
FROM user INNER JOIN local_user ON user.id = local_user.user_id AND user.domain_id = local_user.domain_id
WHERE local_user.name = %(name_1)s AND local_user.domain_id = %(domain_id_1)s) AS anon_1 INNER JOIN local_user ON anon_1.user_id = local_user.user_id AND anon_1.user_domain_id = local_user.domain_id ORDER BY anon_1.user_id, anon_1.user_domain_id
DB_Stats
Nb join : 2
Nb transactions : 0
{domain_id_1, name_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002418
Trace id : 35f9bb7e-1dca-4ae1-85aa-75871673c1db
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT password.id AS password_id, password.local_user_id AS password_local_user_id, password.password AS password_password, password.created_at AS password_created_at, password.expires_at AS password_expires_at, password.self_service AS password_self_service, local_user_1.id AS local_user_1_id
FROM (SELECT user.id AS user_id, user.domain_id AS user_domain_id
FROM user INNER JOIN local_user ON user.id = local_user.user_id AND user.domain_id = local_user.domain_id
WHERE local_user.name = %(name_1)s AND local_user.domain_id = %(domain_id_1)s) AS anon_1 INNER JOIN local_user AS local_user_1 ON anon_1.user_id = local_user_1.user_id AND anon_1.user_domain_id = local_user_1.domain_id INNER JOIN password ON local_user_1.id = password.local_user_id ORDER BY local_user_1.id, password.created_at
DB_Stats
Nb join : 3
Nb transactions : 0
{domain_id_1, name_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001690
Trace id : 466a3df0-8827-4b2b-b797-94f57411f566
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT 1
DB_Stats
Nb join : 0
Nb transactions : 0
{}

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001989
Trace id : aa559bcc-fe41-4b91-9a43-2f7604ebc60c
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT user.enabled AS user_enabled, user.id AS user_id, user.domain_id AS user_domain_id, user.extra AS user_extra, user.default_project_id AS user_default_project_id, user.created_at AS user_created_at, user.last_active_at AS user_last_active_at
FROM user
WHERE user.id = %(param_1)s
DB_Stats
Nb join : 0
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002101
Trace id : 3783cf16-7632-4843-a132-4246f303f379
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT federated_user.id AS federated_user_id, federated_user.user_id AS federated_user_user_id, federated_user.idp_id AS federated_user_idp_id, federated_user.protocol_id AS federated_user_protocol_id, federated_user.unique_id AS federated_user_unique_id, federated_user.display_name AS federated_user_display_name, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.id AS user_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN federated_user ON anon_1.user_id = federated_user.user_id ORDER BY anon_1.user_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002029
Trace id : 81d4c749-b023-4c5c-bf74-c5dc7970daee
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT user_option.user_id AS user_option_user_id, user_option.option_id AS user_option_option_id, user_option.option_value AS user_option_option_value, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.id AS user_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN user_option ON anon_1.user_id = user_option.user_id ORDER BY anon_1.user_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001854
Trace id : 77d9239b-c6a8-465e-a95a-d8f9b1c82979
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT nonlocal_user.domain_id AS nonlocal_user_domain_id, nonlocal_user.name AS nonlocal_user_name, nonlocal_user.user_id AS nonlocal_user_user_id, anon_1.user_domain_id AS anon_1_user_domain_id, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.domain_id AS user_domain_id, user.id AS user_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN nonlocal_user ON anon_1.user_domain_id = nonlocal_user.domain_id AND anon_1.user_id = nonlocal_user.user_id ORDER BY anon_1.user_domain_id, anon_1.user_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002145
Trace id : 329c03f8-6be3-4f2a-9575-de43715afe35
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT local_user.id AS local_user_id, local_user.user_id AS local_user_user_id, local_user.domain_id AS local_user_domain_id, local_user.name AS local_user_name, local_user.failed_auth_count AS local_user_failed_auth_count, local_user.failed_auth_at AS local_user_failed_auth_at, anon_1.user_id AS anon_1_user_id, anon_1.user_domain_id AS anon_1_user_domain_id
FROM (SELECT user.id AS user_id, user.domain_id AS user_domain_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN local_user ON anon_1.user_id = local_user.user_id AND anon_1.user_domain_id = local_user.domain_id ORDER BY anon_1.user_id, anon_1.user_domain_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002266
Trace id : 43bb4f48-f94e-4856-9071-f147579e00ba
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT password.id AS password_id, password.local_user_id AS password_local_user_id, password.password AS password_password, password.created_at AS password_created_at, password.expires_at AS password_expires_at, password.self_service AS password_self_service, local_user_1.id AS local_user_1_id
FROM (SELECT user.id AS user_id, user.domain_id AS user_domain_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN local_user AS local_user_1 ON anon_1.user_id = local_user_1.user_id AND anon_1.user_domain_id = local_user_1.domain_id INNER JOIN password ON local_user_1.id = password.local_user_id ORDER BY local_user_1.id, password.created_at
DB_Stats
Nb join : 2
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001671
Trace id : 6ef84a86-6597-455e-ab47-e6c7bc14b734
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT 1
DB_Stats
Nb join : 0
Nb transactions : 0
{}

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002118
Trace id : 800045f0-0bde-47ba-ab5e-721a40950de7
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT user.enabled AS user_enabled, user.id AS user_id, user.domain_id AS user_domain_id, user.extra AS user_extra, user.default_project_id AS user_default_project_id, user.created_at AS user_created_at, user.last_active_at AS user_last_active_at
FROM user
WHERE user.id = %(param_1)s
DB_Stats
Nb join : 0
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002256
Trace id : d3a86fc6-31c6-4240-99bb-14d15e9f05e1
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT federated_user.id AS federated_user_id, federated_user.user_id AS federated_user_user_id, federated_user.idp_id AS federated_user_idp_id, federated_user.protocol_id AS federated_user_protocol_id, federated_user.unique_id AS federated_user_unique_id, federated_user.display_name AS federated_user_display_name, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.id AS user_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN federated_user ON anon_1.user_id = federated_user.user_id ORDER BY anon_1.user_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001983
Trace id : 0245609c-aad8-4c03-8cde-13a7a105b752
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT user_option.user_id AS user_option_user_id, user_option.option_id AS user_option_option_id, user_option.option_value AS user_option_option_value, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.id AS user_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN user_option ON anon_1.user_id = user_option.user_id ORDER BY anon_1.user_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002044
Trace id : 211d788b-2617-48e2-88cc-1f2b3b836ed7
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT nonlocal_user.domain_id AS nonlocal_user_domain_id, nonlocal_user.name AS nonlocal_user_name, nonlocal_user.user_id AS nonlocal_user_user_id, anon_1.user_domain_id AS anon_1_user_domain_id, anon_1.user_id AS anon_1_user_id
FROM (SELECT user.domain_id AS user_domain_id, user.id AS user_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN nonlocal_user ON anon_1.user_domain_id = nonlocal_user.domain_id AND anon_1.user_id = nonlocal_user.user_id ORDER BY anon_1.user_domain_id, anon_1.user_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002142
Trace id : ee077e09-e891-4094-82c8-1262d3c6d528
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT local_user.id AS local_user_id, local_user.user_id AS local_user_user_id, local_user.domain_id AS local_user_domain_id, local_user.name AS local_user_name, local_user.failed_auth_count AS local_user_failed_auth_count, local_user.failed_auth_at AS local_user_failed_auth_at, anon_1.user_id AS anon_1_user_id, anon_1.user_domain_id AS anon_1_user_domain_id
FROM (SELECT user.id AS user_id, user.domain_id AS user_domain_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN local_user ON anon_1.user_id = local_user.user_id AND anon_1.user_domain_id = local_user.domain_id ORDER BY anon_1.user_id, anon_1.user_domain_id
DB_Stats
Nb join : 1
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.002190
Trace id : 60ea20b8-e5e2-481c-aa23-0d445f85231a
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT password.id AS password_id, password.local_user_id AS password_local_user_id, password.password AS password_password, password.created_at AS password_created_at, password.expires_at AS password_expires_at, password.self_service AS password_self_service, local_user_1.id AS local_user_1_id
FROM (SELECT user.id AS user_id, user.domain_id AS user_domain_id
FROM user
WHERE user.id = %(param_1)s) AS anon_1 INNER JOIN local_user AS local_user_1 ON anon_1.user_id = local_user_1.user_id AND anon_1.user_domain_id = local_user_1.domain_id INNER JOIN password ON local_user_1.id = password.local_user_id ORDER BY local_user_1.id, password.created_at
DB_Stats
Nb join : 2
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001496
Trace id : 2729d1a9-5ea7-4948-ac6d-013e8fa1d0d9
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT 1
DB_Stats
Nb join : 0
Nb transactions : 0
{}

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001724
Trace id : ebb26d6e-55c4-4b49-af31-6fde43d065e2
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT assignment.type AS assignment_type, assignment.actor_id AS assignment_actor_id, assignment.target_id AS assignment_target_id, assignment.role_id AS assignment_role_id, assignment.inherited AS assignment_inherited
FROM assignment
WHERE assignment.actor_id IN (%(actor_id_1)s) AND assignment.target_id IN (%(target_id_1)s) AND assignment.type IN (%(type_1)s) AND assignment.inherited = false
DB_Stats
Nb join : 0
Nb transactions : 0
{type_1, actor_id_1, target_id_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001134
Trace id : 0ee46c5a-958c-4dfc-a107-c0eedd0c382b
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT 1
DB_Stats
Nb join : 0
Nb transactions : 0
{}

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001566
Trace id : af257ec1-f11d-48df-b98b-2b288c1e7b43
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT assignment.type AS assignment_type, assignment.actor_id AS assignment_actor_id, assignment.target_id AS assignment_target_id, assignment.role_id AS assignment_role_id, assignment.inherited AS assignment_inherited
FROM assignment
WHERE assignment.actor_id IN (%(actor_id_1)s) AND assignment.target_id IN (%(target_id_1)s) AND assignment.type IN (%(type_1)s) AND assignment.inherited = true
DB_Stats
Nb join : 0
Nb transactions : 0
{type_1, actor_id_1, target_id_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001095
Trace id : b8b786a0-e568-49c1-98d6-058e745e8a7c
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT 1
DB_Stats
Nb join : 0
Nb transactions : 0
{}

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001685
Trace id : 3d582ea2-cad8-4b52-b6c6-ae546f1b5a39
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr
Statement : SELECT project.id AS project_id, project.name AS project_name, project.domain_id AS project_domain_id, project.description AS project_description, project.enabled AS project_enabled, project.extra AS project_extra, project.parent_id AS project_parent_id, project.is_domain AS project_is_domain
FROM project
WHERE project.id = %(param_1)s
DB_Stats
Nb join : 0
Nb transactions : 0
{param_1, }

DB_COMPONENT
Name : db
Project : keystone
Duration : 0:00:00.001632
Trace id : 3eb3d805-0f4f-471b-8b01-035cff4c487b
Parent id : 25b2e887-66fd-4a60-b860-dbd45fcec9df
Host : parasilo-26-kavlan-5.rennes.grid5000.fr

In [3]:
from ete3 import PhyloTree
# Loads an example tree
nw = """
((Dme_001,Dme_002),(((Cfa_001,Mms_001),((Hsa_001,Ptr_001),Mmu_001)),
(Ptr_002,(Hsa_002,Mmu_002))));
"""
t = PhyloTree(nw)
print(t)

      /-Dme_001
   /-|
  |   \-Dme_002
  |
  |         /-Cfa_001
  |      /-|
--|     |   \-Mms_001
  |   /-|
  |  |  |      /-Hsa_001
  |  |  |   /-|
  |  |   \-|   \-Ptr_001
   \-|     |
     |      \-Mmu_001
     |
     |   /-Ptr_002
      \-|
        |   /-Hsa_002
         \-|
            \-Mmu_002

In [113]:
data = parser.object_data['trace-create-and-delete-image.yaml.json'].children
data2 = parser.object_data['trace-report-boot-and-associate-floating-ip.yaml-f7a3b33f-d2e4-4c6c-8bf0-3782b7b675f8.json'].children
for child in data2:
    print(child.module)

wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi
wsgi

In [153]:
from ete3 import PhyloTree

def scan(parent):

    if len(parent.children) is 0:
        return parent.module
    else:
        data = [ (scanChildren(parent.children[0]), 1) ]
        for child in parent.children[1:]:
            res = scanChildren(child)
            if data[-1][0] == res:
                data[-1] = (data[-1][0], data[-1][1]+1)
            else:
                data.append((res, 1))
        
        dataList = ['{} {}'.format(x[0],x[1]) for x in data]
        return '(' + parent.module + ', (' + ','.join(dataList) + '))'


subTrees = []
for child in data2:
    subTrees.append(scan(child))

treeData = '(' + ','.join(subTrees) + ');'
# print(treeData)
print(PhyloTree(treeData))

   /-wsgi
  |
  |--wsgi
  |
  |   /-wsgi
  |--|
  |   \- /-db 48
  |
  |   /-wsgi
  |  |
  |  |      /-wsgi
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--db 4
  |  |  |
  |   \-|   /-compute_api
  |     |  |
  |     |  |      /-nova_image
  |     |  |     |
  |     |  |   /-|      /-wsgi
  |     |  |  |  |   /-|
  |      \-|  |   \-|   \- /-db
  |        |  |     |
  |        |  |      \-wsgi
  |        |  |
  |        |  |--neutron_api
  |        |  |
  |         \-|--db
  |           |
  |           |--compute_api
  |           |
  |           |   /-rpc
  |           |  |
  |           |  |   /-db
  |           |  |  |
  |           |  |  |   /-rpc
  |            \-|  |--|
  |              |  |   \- /-rpc
  |              |  |
  |              |  |   /-rpc
  |              |  |  |
  |               \-|  |      /-rpc
  |                 |  |     |
  |                 |  |     |      /-rpc
  |                 |  |     |   /-|
  |                 |  |     |  |   \- /-db
  |                 |  |     |  |
  |                 |  |     |  |   /-rpc
  |                 |  |     |  |--|
  |                 |  |     |  |   \- /-db
  |                  \-|     |  |
  |                    |     |  |   /-rpc
  |                    |     |  |--|
  |                    |     |  |   \- /-db
  |                    |     |  |
  |                    |     |  |   /-rpc
  |                    |     |  |--|
  |                    |     |  |   \- /-db
  |                    |     |  |
  |                    |     |  |   /-rpc
  |                    |     |  |--|
  |                    |     |  |   \- /-db
  |                     \- /-|  |
  |                          |  |   /-rpc
  |                          |  |--|
  |                          |  |   \- /-db
  |                          |  |
  |                          |  |   /-rpc
  |                          |  |--|
  |                          |  |   \- /-db
  |                          |  |
  |                          |  |--neutron_api
  |                          |  |
  |                          |  |   /-rpc
  |                          |  |--|
  |                          |  |   \- /-db
  |                          |  |
  |                          |  |   /-rpc
  |                          |  |--|
  |                          |  |   \- /-db
  |                          |  |
  |                          |  |   /-rpc
  |                          |  |--|
  |                          |  |   \- /-db
  |                           \-|
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |   /-vif_driver
  |                             |--|
  |                             |   \- /-vif_driver
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |--vif_driver
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-db
  |                             |
  |                             |   /-rpc
  |                             |--|
  |                             |   \- /-rpc
  |                             |
  |                             |   /-rpc
  |                              \-|
  |                                 \- /-db
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |  |  |--db 2
  |   \-|
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |  |  |--db 2
  |   \-|
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |   \-|--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |   \-|--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |   \-|--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |   \-|--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |--|   /-|
  |  |  |   \- /-db
  |  |  |
  |   \-|--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
--|  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |--|
  |   \- /-neutron.db 20
  |
  |   /-wsgi
  |  |
  |  |   /-neutron.db 179
  |--|  |
  |  |  |--rpc 1
  |  |  |
  |   \-|--neutron.db 82
  |     |
  |     |--rpc 1
  |     |
  |      \-neutron.db 8
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |  |  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |  |  |--|
  |  |  |   \- /-neutron_api
  |  |  |
  |  |  |--neutron_api 1
  |--|  |
  |  |  |   /-neutron_api
  |  |  |--|
  |  |  |   \- /-neutron_api
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |  |  |--|
  |  |  |   \- /-neutron_api
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |     |--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |     |--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |     |--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
  |--|  |   \- /-db
  |  |  |
  |  |  |--neutron_api 1
  |  |  |
  |  |  |   /-neutron_api
  |   \-|--|
  |     |   \- /-neutron_api
  |     |
  |     |--neutron_api 1
  |     |
  |     |   /-neutron_api
  |      \-|
  |         \- /-neutron_api
  |
  |   /-wsgi
  |  |
  |  |      /-compute_api
  |  |   /-|
   \-|  |   \- /-db
     |  |
     |  |--neutron_api 1
     |  |
     |  |   /-neutron_api
      \-|--|
        |   \- /-neutron_api
        |
        |--neutron_api 1
        |
        |   /-neutron_api
         \-|
            \- /-neutron_api

In [107]:
from json_parser import JsonParser
parser = JsonParser()
print(parser.files)

['/Users/billy/Documents/workspace/FIL/A3/Openstack-SQL/OpenstackSQLAnalyzer/src/../files/trace-create-and-delete-image.yaml.json', '/Users/billy/Documents/workspace/FIL/A3/Openstack-SQL/OpenstackSQLAnalyzer/src/../files/trace-report-boot-and-associate-floating-ip.yaml-f7a3b33f-d2e4-4c6c-8bf0-3782b7b675f8.json']

In [146]:
d = [('a,',0), ('b',1), ('c',1), ('d',3), ('f',6)]

for x in d[1:]:
    print(x)


# dataList = ['{} {}'.format(x[0],x[1]) for x in d]
# dataList

('b', 1)
('c', 1)
('d', 3)
('f', 6)

In [159]:
keys = parser.object_data.keys()
print(keys)
for k in keys:
    print(k)

dict_keys(['trace-create-and-delete-image.yaml.json'])
trace-create-and-delete-image.yaml.json